USER_BATCH_SIZE = 500

# FREE
LIMIT_BETWEEN_REQUESTS_SECONDS = 30
GPT3_MONTHLY_LIMIT_MESSAGES_FREE = 100
GPT4_MONTHLY_LIMIT_MESSAGES_FREE = 0
ADDITIONAL_CHATS_LIMIT_FREE = 0
DALLE3_MONTHLY_LIMIT_IMAGES_FREE = 0
FACE_SWAP_MONTHLY_LIMIT_IMAGES_FREE = 0

# STANDARD ⭐
GPT3_MONTHLY_LIMIT_MESSAGES_STANDARD = 300
GPT4_MONTHLY_LIMIT_MESSAGES_STANDARD = 10
ADDITIONAL_CHATS_LIMIT_STANDARD = 1
DALLE3_MONTHLY_LIMIT_IMAGES_STANDARD = 10
FACE_SWAP_MONTHLY_LIMIT_IMAGES_STANDARD = 20

# VIP 🔥
GPT3_MONTHLY_LIMIT_MESSAGES_VIP = 1000
GPT4_MONTHLY_LIMIT_MESSAGES_VIP = 50
ADDITIONAL_CHATS_LIMIT_VIP = 5
DALLE3_MONTHLY_LIMIT_IMAGES_VIP = 20
FACE_SWAP_MONTHLY_LIMIT_IMAGES_VIP = 50

# PLATINUM 💎
GPT3_MONTHLY_LIMIT_MESSAGES_PLATINUM = 2000
GPT4_MONTHLY_LIMIT_MESSAGES_PLATINUM = 100
ADDITIONAL_CHATS_LIMIT_PLATINUM = 10
DALLE3_MONTHLY_LIMIT_IMAGES_PLATINUM = 50
FACE_SWAP_MONTHLY_LIMIT_IMAGES_PLATINUM = 100

PARSE_MODE = 'Markdown'
